/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AntiqueCertification__factory } from "./AntiqueCertification__factory";
export { AntiqueCertificationIssuance__factory } from "./AntiqueCertificationIssuance__factory";
export { AntiqueVerification__factory } from "./AntiqueVerification__factory";
export { Dummy__factory } from "./Dummy__factory";
