/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AntiqueCertification } from "./AntiqueCertification";
export type { AntiqueCertificationIssuance } from "./AntiqueCertificationIssuance";
export type { AntiqueVerification } from "./AntiqueVerification";
export type { Dummy } from "./Dummy";
export * as factories from "./factories";
export { AntiqueCertification__factory } from "./factories/AntiqueCertification__factory";
export { AntiqueCertificationIssuance__factory } from "./factories/AntiqueCertificationIssuance__factory";
export { AntiqueVerification__factory } from "./factories/AntiqueVerification__factory";
export { Dummy__factory } from "./factories/Dummy__factory";
